[package]
authors = ["deciduously <ben@deciduously.com>"]
edition = "2018"
name = "fivedice"
description = "WASM Yahtzee"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/deciduously/fivedice.git"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.js-sys]
version = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
    "Attr",
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Text",
    "Window"
]