[package]
authors = ["deciduously <ben@deciduously.com>"]
edition = "2018"
name = "fivedice"
description = "WASM Yahtzee"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/deciduously/fivedice.git"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "Attr",
    "CanvasRenderingContext2d",
    "Document",
    "DomRect",
    "DomRectReadOnly",
    "Element",
    "Event",
    "EventTarget",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "MouseEvent",
    "Node",
    "Text",
    "Window"
]